### ISSUE TITLE
Bug/Question: Initial build/dev fails... while second execution works

### ISSUE THREAD

**Issue by swernerx** [oedotme/generouted#33] opened 2022-12-06 20:52 UTC
Has anybody ever seen the following issue with Generouted and React Router?

When I am deleting `node_modules/.vite` to force refresh the build or when clean installing `node_modules` I get a somewhat confusing error where the client side application is reporting context errors like:

```
utils.ts:784 Uncaught Error: useHref() may be used only in the context of a <Router> component.
```

The stack trace shows all the routing specific components ... e.g. `RouterProvider`.

The funny thing is: when stopping the dev server and restarting it everything works fine. As if something get cached somehow during the first execution and fixes the second time execution.

**Comment by swernerx** [comment] 2022-12-06 21:01
Also happens when executing the dev-server with `--force` to ignore any Vite caches.

**Comment by swernerx** [comment] 2022-12-07 09:36
Probably related to this issue: https://github.com/vitejs/vite/issues/11238

**Comment by oedotme** [comment] 2022-12-07 21:40
I haven't faced that issue no, I tried to manually remove the `node_modules/.vite` directory or use the `--force` argument and still couldn't see the issue. The project doesn't use `useHref` hook though, I'll try to reproduce it in a another project.

BTW Which Vite version and operating system are you using?

**Comment by oedotme** [comment] 2022-12-09 08:21
Hey @swernerx, I tried in a new project with React Router w/ `useHref` usage, and only had a warning for missing source maps. Didn't face any errors though.

I found the versions details in the related issue you've mentioned, and I'm also running the same versions.

**Comment by t-animal** [comment] 2023-03-13 12:10
We also get the same problem when using `useMatch`

**Comment by t-animal** [comment] 2023-03-14 08:19
Some first tests indicate that switchign to `import { Routes } from "generouted/react-router-lazy";` might help.

**Comment by oedotme** [comment] 2023-03-15 08:11
@t-animal I found this issue in both `generouted/react-router` and `generouted/react-router-lazy`.

It works with both integrations though if you restart the server as @swernerx pointed out.

One possible solution I tried yesterday, is to import `routes` instead of `Routes` and to use `RouterProvider` in your application entry, so instead of:

```tsx
import { Routes } from 'generouted/react-router'

root.render(<Routes />, ...)
```

You could:

```tsx
import { createBrowserRouter, RouterProvider } from 'react-router-dom'
import { routes } from 'generouted/react-router'

root.render(<RouterProvider router={createBrowserRouter(routes)} />, ...)
```

That fixed the issue, which is similar to what @swernerx already mentioned in a related issue that importing and using anything from `react-router-dom` results in no errors in the initial server start.

I believe the issue is in Vite, and from my testing I found there's file version hashes mismatch in the first server start which delays or causes issues with `react-router-dom` resolving as a dependency, but in the subsequent runs the file hash matches and works without issues.

**Comment by oedotme** [comment] 2023-03-29 08:41
Seems to be fixed now after introducing bundling a `js` version for the `react-router` integration. You can test it with the latest `generouted` version and usage at [v1.12.0](https://github.com/oedotme/generouted/releases/tag/v1.12.0).


> I believe the issue is in Vite, and from my testing I found there's file version hashes mismatch in the first server start which delays or causes issues with react-router-dom resolving as a dependency, but in the subsequent runs the file hash matches and works without issues.

Maybe it's resolved now as the source is already transformed so the hashing is more consistent.

I'll close this issue, feel free to reopen if encountered that again.

**Closed by oedotme** 2023-03-29 08:41 UTC
